In [1]:
import pandas as pd

/tmp/ipykernel_5782/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
pd.__version__

'2.2.0'

In [3]:
df = pd.read_csv('green_tripdata_2019-01.csv', nrows=100)

In [4]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2018-12-21 15:17:29,2018-12-21 15:18:57,N,1,264,264,5,0.00,3.0,0.5,0.5,0.00,0.0,NaN,0.3,4.30,2,1,NaN
1,2,2019-01-01 00:10:16,2019-01-01 00:16:32,N,1,97,49,2,0.86,6.0,0.5,0.5,0.00,0.0,NaN,0.3,7.30,2,1,NaN
2,2,2019-01-01 00:27:11,2019-01-01 00:31:38,N,1,49,189,2,0.66,4.5,0.5,0.5,0.00,0.0,NaN,0.3,5.80,1,1,NaN
3,2,2019-01-01 00:46:20,2019-01-01 01:04:54,N,1,189,17,2,2.68,13.5,0.5,0.5,2.96,0.0,NaN,0.3,19.71,1,1,NaN
4,2,2019-01-01 00:19:06,2019-01-01 00:39:43,N,1,82,258,1,4.53,18.0,0.5,0.5,0.00,0.0,NaN,0.3,19.30,2,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2,2019-01-01 00:15:42,2019-01-01 00:41:04,N,1,97,179,1,7.83,26.0,0.5,0.5,5.46,0.0,NaN,0.3,32.76,1,1,NaN
96,2,2019-01-01 00:21:28,2019-01-01 00:48:15,N,1,7,230,1,4.49,20.0,0.5,0.5,4.00,0.0,NaN,0.3,25.30,1,1,NaN
97,2,2019-01-01 00:17:10,2019-01-01 00:23:34,N,1,42,42,1,1.08,6.5,0.5,0.5,0.00,0.0,NaN,0.3,7.80,2,1,NaN
98,2,2019-01-01 00:25:01,2019-01-01 00:43:55,N,1,42,232,2,8.74,25.0,0.5,0.5,0.00,0.0,NaN,0.3,26.30,2,1,NaN
99,2,2019-01-01 00:36:56,2019-01-01 00:43:50,N,1,223,7,5,1.32,7.0,0.5,0.5,2.00,0.0,NaN,0.3,10.30,1,1,NaN

In [5]:
print(pd.io.sql.get_schema(df, name = 'green_texi_data'))

CREATE TABLE "green_texi_data" (
"VendorID" INTEGER,
  "lpep_pickup_datetime" TEXT,
  "lpep_dropoff_datetime" TEXT,
  "store_and_fwd_flag" TEXT,
  "RatecodeID" INTEGER,
  "PULocationID" INTEGER,
  "DOLocationID" INTEGER,
  "passenger_count" INTEGER,
  "trip_distance" REAL,
  "fare_amount" REAL,
  "extra" REAL,
  "mta_tax" REAL,
  "tip_amount" REAL,
  "tolls_amount" REAL,
  "ehail_fee" REAL,
  "improvement_surcharge" REAL,
  "total_amount" REAL,
  "payment_type" INTEGER,
  "trip_type" INTEGER,
  "congestion_surcharge" REAL
)

In [6]:
pd.to_datetime(df.lpep_pickup_datetime)

0    2018-12-21 15:17:29
1    2019-01-01 00:10:16
2    2019-01-01 00:27:11
3    2019-01-01 00:46:20
4    2019-01-01 00:19:06
             ...
95   2019-01-01 00:15:42
96   2019-01-01 00:21:28
97   2019-01-01 00:17:10
98   2019-01-01 00:25:01
99   2019-01-01 00:36:56
Name: lpep_pickup_datetime, Length: 100, dtype: datetime64[ns]

In [7]:
df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)

In [8]:
from sqlalchemy import create_engine

In [11]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [12]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [13]:
from sqlalchemy import create_engine

In [14]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')
engine.connect()

OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [15]:
print(pd.io.sql.get_schema(df, name = 'green_texi_data', con=engine))

OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [23]:
df_iter = pd.read_csv('green_tripdata_2019-01.csv', iterator=True, chunksize=100000)

In [25]:
df_iter = pd.read_csv('green_tripdata_2019-01.csv', iterator=True, chunksize=100000)
df=next(df_iter)
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2018-12-21 15:17:29,2018-12-21 15:18:57,N,1,264,264,5,0.00,3.00,0.5,0.5,0.00,0.00,NaN,0.3,4.30,2,1,NaN
1,2,2019-01-01 00:10:16,2019-01-01 00:16:32,N,1,97,49,2,0.86,6.00,0.5,0.5,0.00,0.00,NaN,0.3,7.30,2,1,NaN
2,2,2019-01-01 00:27:11,2019-01-01 00:31:38,N,1,49,189,2,0.66,4.50,0.5,0.5,0.00,0.00,NaN,0.3,5.80,1,1,NaN
3,2,2019-01-01 00:46:20,2019-01-01 01:04:54,N,1,189,17,2,2.68,13.50,0.5,0.5,2.96,0.00,NaN,0.3,19.71,1,1,NaN
4,2,2019-01-01 00:19:06,2019-01-01 00:39:43,N,1,82,258,1,4.53,18.00,0.5,0.5,0.00,0.00,NaN,0.3,19.30,2,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2,2019-01-06 09:56:09,2019-01-06 10:01:30,N,1,130,216,1,1.23,6.00,0.0,0.5,0.00,0.00,NaN,0.3,6.80,2,1,NaN
99996,2,2019-01-06 09:12:49,2019-01-06 09:52:38,N,5,218,16,1,21.44,47.65,0.0,0.5,0.00,5.76,NaN,0.0,53.91,1,2,NaN
99997,2,2019-01-06 09:02:06,2019-01-06 09:37:42,N,5,139,188,1,14.77,37.84,0.0,0.5,0.00,0.00,NaN,0.0,38.34,1,2,NaN
99998,2,2019-01-06 09:55:01,2019-01-06 10:04:34,N,1,72,188,1,1.80,8.50,0.0,0.5,0.00,0.00,NaN,0.3,9.30,1,1,NaN
99999,2,2019-01-06 09:59:04,2019-01-06 10:24:33,N,5,89,225,1,7.03,23.14,0.0,0.5,0.00,0.00,NaN,0.0,23.64,1,2,NaN

In [26]:
df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime) #text转timestamp
df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)

In [27]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2018-12-21 15:17:29,2018-12-21 15:18:57,N,1,264,264,5,0.00,3.0,0.5,0.5,0.00,0.0,NaN,0.3,4.30,2,1,NaN
1,2,2019-01-01 00:10:16,2019-01-01 00:16:32,N,1,97,49,2,0.86,6.0,0.5,0.5,0.00,0.0,NaN,0.3,7.30,2,1,NaN
2,2,2019-01-01 00:27:11,2019-01-01 00:31:38,N,1,49,189,2,0.66,4.5,0.5,0.5,0.00,0.0,NaN,0.3,5.80,1,1,NaN
3,2,2019-01-01 00:46:20,2019-01-01 01:04:54,N,1,189,17,2,2.68,13.5,0.5,0.5,2.96,0.0,NaN,0.3,19.71,1,1,NaN
4,2,2019-01-01 00:19:06,2019-01-01 00:39:43,N,1,82,258,1,4.53,18.0,0.5,0.5,0.00,0.0,NaN,0.3,19.30,2,1,NaN

In [28]:
df.head(n=0)

Empty DataFrame
Columns: [VendorID, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, RatecodeID, PULocationID, DOLocationID, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type, congestion_surcharge]
Index: []

In [29]:
df.to_sql(name = 'green_texi_data', con=engine,if_exists='replace')

1000

In [30]:
df.head(n=0).to_sql(name = 'green_texi_data',con=engine,if_exists='replace')

0

In [31]:
df.head(n=0).to_sql(name = 'green_texi_data',con=engine,if_exists='replace')

0

In [32]:
%time df.to_sql(name='green_texi_data', con=engine, if_exists='append')

CPU times: user 6.12 s, sys: 35.7 ms, total: 6.15 s
Wall time: 8.49 s

1000

In [34]:
while Ture:
	df = next(df_iter)
	df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime) #text转timestamp
    df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)
    df.to_sql(name='green_texi_data', con=engine, if_exists='append')
    print('insert another chunk'')

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 4)

In [37]:
from time import time
while True:
    t_start=time()
    df = next(df_iter)
    df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime) #text转timestamp
    df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)
    df.to_sql(name='green_texi_data', con=engine, if_exists='append')
    t_end = time()
    print('insert another chunk... took %.3f sec' % (t_end - t_start))

insert another chunk... took %.3f sec%(t_end-t_start)
insert another chunk... took %.3f sec%(t_end-t_start)
insert another chunk... took %.3f sec%(t_end-t_start)
insert another chunk... took %.3f sec%(t_end-t_start)
insert another chunk... took %.3f sec%(t_end-t_start)
insert another chunk... took %.3f sec%(t_end-t_start)

StopIteration:

In [38]:
print('insert another chunk... took %.3f sec' % (t_end - t_start))

insert another chunk... took -0.000 sec

In [39]:
df = pd.read_csv('green_tripdata_2019-01.csv')

In [40]:
len(df)

630918